#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jmh-gradle-plugin
Version  : elease.0.4.5
Release  : 4
URL      : https://github.com/melix/jmh-gradle-plugin/archive/RELEASE_0_4_5.tar.gz
Source0  : https://github.com/melix/jmh-gradle-plugin/archive/RELEASE_0_4_5.tar.gz
Source1  : https://plugins.gradle.org/m2/me/champeau/gradle/jmh-gradle-plugin/0.4.5-beta-1/jmh-gradle-plugin-0.4.5-beta-1.jar
Source2  : https://plugins.gradle.org/m2/me/champeau/gradle/jmh-gradle-plugin/0.4.5-beta-1/jmh-gradle-plugin-0.4.5-beta-1.pom
Source3  : https://plugins.gradle.org/m2/me/champeau/gradle/jmh-gradle-plugin/0.4.8/jmh-gradle-plugin-0.4.8.jar
Source4  : https://plugins.gradle.org/m2/me/champeau/gradle/jmh-gradle-plugin/0.4.8/jmh-gradle-plugin-0.4.8.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jmh-gradle-plugin-data = %{version}-%{release}
Requires: mvn-jmh-gradle-plugin-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
= JMH Gradle Plugin
:jmh-version: 1.19
:plugin-version: 0.4.5
image:http://img.shields.io/travis/melix/jmh-gradle-plugin/master.svg["Build Status (travis)", link="https://travis-ci.org/melix/jmh-gradle-plugin"]
image:http://img.shields.io/coveralls/melix/jmh-gradle-plugin/master.svg["Coverage Status (coveralls)", link="https://coveralls.io/r/melix/jmh-gradle-plugin"]
image:https://api.bintray.com/packages/melix/gradle-plugins/jmh-gradle-plugin/images/download.svg[Download, link="https://bintray.com/melix/gradle-plugins/jmh-gradle-plugin"]
image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"]

%package data
Summary: data components for the mvn-jmh-gradle-plugin package.
Group: Data

%description data
data components for the mvn-jmh-gradle-plugin package.


%package license
Summary: license components for the mvn-jmh-gradle-plugin package.
Group: Default

%description license
license components for the mvn-jmh-gradle-plugin package.


%prep
%setup -q -n jmh-gradle-plugin-RELEASE_0_4_5

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jmh-gradle-plugin
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-jmh-gradle-plugin/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/me/champeau/gradle/jmh-gradle-plugin/0.4.5-beta-1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/me/champeau/gradle/jmh-gradle-plugin/0.4.5-beta-1/jmh-gradle-plugin-0.4.5-beta-1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/me/champeau/gradle/jmh-gradle-plugin/0.4.5-beta-1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/me/champeau/gradle/jmh-gradle-plugin/0.4.5-beta-1/jmh-gradle-plugin-0.4.5-beta-1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/me/champeau/gradle/jmh-gradle-plugin/0.4.8
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/me/champeau/gradle/jmh-gradle-plugin/0.4.8/jmh-gradle-plugin-0.4.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/me/champeau/gradle/jmh-gradle-plugin/0.4.8
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/me/champeau/gradle/jmh-gradle-plugin/0.4.8/jmh-gradle-plugin-0.4.8.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/me/champeau/gradle/jmh-gradle-plugin/0.4.5-beta-1/jmh-gradle-plugin-0.4.5-beta-1.jar
/usr/share/java/.m2/repository/me/champeau/gradle/jmh-gradle-plugin/0.4.5-beta-1/jmh-gradle-plugin-0.4.5-beta-1.pom
/usr/share/java/.m2/repository/me/champeau/gradle/jmh-gradle-plugin/0.4.8/jmh-gradle-plugin-0.4.8.jar
/usr/share/java/.m2/repository/me/champeau/gradle/jmh-gradle-plugin/0.4.8/jmh-gradle-plugin-0.4.8.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jmh-gradle-plugin/LICENSE
